administration/urls.py
from django.urls import path

from .views import (
        choose, upload_data, 
        resaults, 
        privileges, 
        approval, 
        subjects_report, 
        reports,
        download_compressed_folder
    )

app_name = "administration"

urlpatterns = [
    path('', choose, name="choose"),
    path('upload/', upload_data, name="upload_data"),
    path('results/', resaults, name="resaults"),
    path('privileges/', privileges, name="privileges"),
    path('approval/', approval, name="approval"),
    path('subjects/data/', subjects_report, name="subjects_report"),
    path('subjects/reports/', reports, name="reports"),
    path('results/download-compressed-folder/', download_compressed_folder, name="download_compressed_folder")
]

docss/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('researches/', include('researches.urls')),
    path('administration/', include('administration.urls')),
    path('unistruct/', include('unistruct.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

researches/urls.py
from django.urls import path
from .views import (
        main, 
        create_topic, 
        select_topic, 
        upload_research, 
        correcting,
        students_resaults,
    )

app_name="researches"

urlpatterns = [
    path('', main, name="main"),
    path('<int:id>/doctor/topics/', create_topic, name="create_topic"),
    path('<int:id>/topics/select/', select_topic, name="select_topic_to_correct"),
    path('<int:sid>/<int:rid>/upload/', upload_research, name="upload_research"),
    path('<int:sid>/<int:rid>/correcting/', correcting, name="correcting"),
    path('students_resaults/', students_resaults, name="students_resaults"),
]

unistruct/urls.py
from django.urls import path

from .views import adding_subjects

app_name = "unistruct"

urlpatterns = [
    path('', adding_subjects, name="adding_subjects")
]

users/urls.py
from django.urls import path
from .views import home, loginView, logout_view, create_passwd, passwd_login

app_name="users"

urlpatterns = [
    path('', home, name="home"),
    path('<str:prof>/login/', loginView, name="login"),
    path('<str:prof>/create_password/', create_passwd, name="create_passwd"),
    path('<str:prof>/password_login/', passwd_login, name="passwd_login"),

    path('logout/', logout_view, name="logout")
]

administration/models.py
from django.db import models

# Create your models here.

administration/views.py
import xlrd
import os
import zipfile
import io


from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required, user_passes_test
from django.utils.datastructures import MultiValueDictKeyError
from django.conf import settings
from django.http import HttpResponse

from unistruct.models import Faculty, Team, Department, Section, Subject
from users.models import User
from researches.models import Research, StudentResearch

# Create your views here.

@login_required
@user_passes_test(
    lambda u: u.doctor,
    redirect_field_name="researches:main"
)
def choose(request):
    return render(request, 'administration/choose.html', {})

@login_required
@user_passes_test(
    lambda u: u.staff,
    redirect_field_name="researches:main"
)
def upload_data(request):
    if request.method == "POST":
        files = request.FILES
        # SUBJECTS
        try:
            input_excel = files['subjects']

            wb = xlrd.open_workbook(file_contents = input_excel.read(), encoding_override = 'utf8')
            sheet = wb.sheet_by_index(0)
            for i in range(1, sheet.nrows-1):
                cv = sheet.row_values(i)
                facl = str(cv[4]).strip()
                sec = str(cv[3]).strip()
                dprt = str(cv[2]).strip()
                tem = str(cv[1]).strip()
                subj = str(cv[0]).strip()

                faculty, _ = Faculty.objects.get_or_create(name=facl)
                team, _ = Team.objects.get_or_create(name=tem, faculty=faculty)
                department, _ = Department.objects.get_or_create(name=dprt, faculty=faculty)
                section, _ = Section.objects.get_or_create(name=sec, department=department)
                subject, _ = Subject.objects.get_or_create(name=subj, section=section, team=team)

        except MultiValueDictKeyError:
            pass

        except:
            print('error')

        # MEMBERS
        try:
            input_excel = files['members']
            
            wb = xlrd.open_workbook(file_contents = input_excel.read(), encoding_override = 'utf8')
            sheet = wb.sheet_by_index(0)

            for i in range(1, sheet.nrows-1):
                cv = sheet.row_values(i)
                mfacl = str(cv[2]).strip()
                mdprt = str(cv[3]).strip()
                ni = str(int(float(str(cv[0]))))
                mbr = str(cv[1]).strip()


                mfaculty, _ = Faculty.objects.get_or_create(name=mfacl)
                mdepartment, _ = Department.objects.get_or_create(name=mdprt, faculty=mfaculty)
                try:
                    member, _ = User.objects.get_or_create(
                        national_id= ni,
                        name = mbr,
                        doctor = True,
                        faculty=mfaculty,
                        department= mdepartment,
                        password= "doc"
                    )
                except:
                    pass

        except MultiValueDictKeyError:
            pass

        except:
            print('error')
        



        # STUDENTS
        try:
            input_excel = files['students']

            wb = xlrd.open_workbook(file_contents = input_excel.read(), encoding_override = 'utf8')
            sheet = wb.sheet_by_index(0)

            for i in range(1, sheet.nrows):
                cv = sheet.row_values(i)

                ni = str(int(float(str(cv[0]))))
                mbr = str(cv[1]).strip()
                facl = str(cv[2]).strip()
                tem = str(cv[3]).strip()
                stem = str(cv[5]).strip()
                dprt = str(cv[6]).strip()
                sec = str(cv[7]).strip()
                subj = str(cv[8]).strip()
                email, emailpasswd = None, None
                if len(cv) == 11 :
                    email = str(cv[9]).strip() 
                    emailpasswd = str(cv[10]).strip() 
                
                faculty, _ = Faculty.objects.get_or_create(name=facl)
                team, _ = Team.objects.get_or_create(name=tem, faculty=faculty)
                steam, _ = Team.objects.get_or_create(name=stem, faculty=faculty)
                department, _ = Department.objects.get_or_create(name=dprt, faculty=faculty)
                section, _ = Section.objects.get_or_create(name=sec, department=department)
                subject, _ = Subject.objects.get_or_create(name=subj, section=section, team=steam)
                if len(User.objects.filter(national_id=ni)) == 1:
                    student = User.objects.get(national_id=ni) 
                    if email and emailpasswd:
                        student.official_email = email 
                        student.official_email_passwd = emailpasswd
                        student.save()
                    student.subjects.add(subject)
                else:
                    try:
                        student, _ = User.objects.get_or_create(
                            national_id= ni,
                            name = mbr,
                            doctor = False,
                            faculty=faculty,
                            team= team,
                            password= "stu"
                        )

                        student.subjects.add(subject)
                        if email and emailpasswd:
                            student.official_email = email
                            student.official_email_passwd = emailpasswd
                            student.save()
                    except:
                        pass

        except MultiValueDictKeyError:
            pass

        except:
            raise ValueError('Error')

    return render(request, 'administration/upload_data.html', {})

@login_required
@user_passes_test(
    lambda u: u.control_head,
    redirect_field_name="researches:main"
)
def resaults(request):
    context = {
        "students": User.objects.filter(doctor=False),
        "faculties": Faculty.objects.all()}
    return render(request, 'administration/resaults.html', context)

@login_required
@user_passes_test(
    lambda u: u.staff,
    redirect_field_name="researches:main"
)
def privileges(request):
    context = {}
    if request.user.admin:
        context['faculties'] = Faculty.objects.all()
    else:
        context['teams'] = request.user.faculty.teams.all()
    if request.method == "POST":
        post = list(dict(request.POST).items())[1:]

        if request.user.admin:
            for d in post:
                dean = User.objects.get(national_id=d[1][0])
                dean.staff=True
                dean.control_head = True
                dean.save()
        else:
            for ch in post:
                control_head = User.objects.get(national_id=ch[1][0])
                control_head.control_head=True
                control_head.team = Team.objects.get(id=int(ch[0]))
                control_head.save()

    return render(request, 'administration/privileges.html', context)

@login_required
@user_passes_test(
    lambda u: u.control_head,
    redirect_field_name="researches:main"
)
def approval(request):
    context = {'faculties': Faculty.objects.all()}
    if request.method == "POST":
        try:
            post = list(dict(request.POST).keys())[1:]
        except:
            post = []
        if request.user.staff:
            for team_id in post:
                team = Team.objects.get(id=int(team_id))
                team.done = True
                team.save() 
        else:
            for subject_id in post:
                subject = Subject.objects.get(id=int(subject_id))
                subject.done = True
                subject.save() 
    return render(request, 'administration/approval.html', context)


@login_required
@user_passes_test(
    lambda u: u.staff or u.dprtmngr,
    redirect_field_name="researches:main"
)
def subjects_report(request):
    member = request.user

    if member.admin:
        context = {
            'faculties': Faculty.objects.order_by('name'),
        }
    elif member.staff:
        context = {
            'entries':member.faculty.members_list,
            'departments': member.faculty.departments_list,
            'subjs_number': member.faculty.subjs_number,
        }
    else:
        context = {
            'entries': member.department.members_list,
            'departments': member.faculty.departments.filter(name=member.department),
            'subjs_number': member.department.subjs_number,
        }

    return render(request, 'administration/subjects_report.html', context)


@login_required
@user_passes_test(
    lambda u: u.control_head,
    redirect_field_name="researches:main"
)
def reports(request):
    context = {
        "subjects": Subject.objects.all(),
        "faculties": Faculty.objects.all()}
    return render(request, 'administration/reports.html', context)

@login_required
@user_passes_test(
    lambda u: u.control_head and not u.staff,
    redirect_field_name="researches:main"
)
def download_compressed_folder(request):
    # Folder name in ZIP archive which contains the above files
    # E.g [thearchive.zip]/somefiles/file2.txt
    # FIXME: Set this to something better
    zip_dir_name = f"student_researches"
    zip_filename = f"{zip_dir_name}.zip"

    # Open StringIO to grab in-memory ZIP contents
    s = io.BytesIO()

    # The zip compressor
    zf = zipfile.ZipFile(s, "w")

    for sr in StudentResearch.objects.filter(research__subject__in=request.user.team.subjects.all()):
        # Calculate path for file in zip
        zip_path = os.path.join(zip_dir_name, sr.research_file.name)

        # Add file, at correct path
        zf.write(os.path.join(settings.MEDIA_ROOT, sr.research_file.name), zip_path)

    # Must close zip for all contents to be written
    zf.close()

    # Grab ZIP file from in-memory, make response with correct MIME-type
    resp = HttpResponse(s.getvalue(), content_type = "application/x-zip-compressed")

administration/templates/administration/choose.html
{% extends 'base.html' %}
{% load static %}


{% block extrastyle %}
    <link rel="stylesheet" href="{% static 'css/admin-1.css' %}" />
    <link rel="stylesheet" href="{% static 'css/send-research.css' %}" />
    <style>
        .manage-btn, .manage-btn a{
		background-color: rgb(0, 130, 182)!important;
		font-size: 1.3em;
	}
    </style>
{% endblock extrastyle %}
    

{% block title %}إدارة المنصة{% endblock title %}

{% block body %}
    <div class="box">
        <div class="row">
            <div class="col-lg-12 col-md-12 right">
                <div class="professor">
                    <img class="img-fluid" src="/media/images/professor2.png" alt="عضو هيئة تدريس" id="type-f-img">
                    <span id="name-span" class="name">{{ request.user.name }}</span>
                    <p class="choosed title">
                        {% if request.user.admin %}المدير
                        {% elif request.user.staff %}عميد
                        {% elif request.user.control_head %}رئيس كنترول
                        {% elif request.user.dprtmngr %}رئيس قسم
                        {% endif %}
                            
                    </p>
                    <p class="choosed name">إدارة المنصة</p>

                </div>
            </div>           
            {% if request.user.admin %}
                <section class="exit-buttons col-12" style="margin-top:20px;">
                    <button class="save manage-btn" type="button" style="width:80% ; padding: 15px;"><a href="{% url 'administration:upload_data' %}" style="background-color:rgb(255, 179, 0); ">إدخال البيانات</a></button>
                </section>
                <section class="exit-buttons col-12" style="margin-top:20px;">
                    <button class="save manage-btn" type="button" style="width:80% ; padding: 15px;"><a href="{% url 'administration:privileges' %}" style="background-color:rgb(255, 179, 0); ">وضع الصلاحيات</a></button>
                </section>
                <section class="exit-buttons col-12" style="margin-top:20px;">
                    <button class="save manage-btn" type="button" style="width:80% ; padding: 15px;"><a href="{% url 'unistruct:adding_subjects' %}" style="background-color:rgb(255, 179, 0); ">إضافة المقررات التي أقوم بتدريسها</a></button>
                </section>
                <section class="exit-buttons col-12" style="margin-top:20px;">
                    <button class="save manage-btn" type="button" style="width:80% ; padding: 15px;"><a href="{% url 'administration:subjects_report' %}" style="background-color:rgb(255, 179, 0); ">بيانات تسجيل المقررات</a></button>
                </section>
                <section class="exit-buttons col-12" style="margin-top:20px;">
                    <button class="save manage-btn" type="button" style="width:80% ; padding: 15px;"><a href="{% url 'researches:main' %}" style="background-color:rgb(255, 179, 0); ">الموضوعات البحثية</a></button>
                </section>
                <section class="exit-buttons col-12" style="margin-top:20px;">
                    <button class="save manage-btn" type="button" style="width:80% ; padding: 15px;"><a href="{% url 'administration:reports' %}" style="background-color:rgb(255, 179, 0); ">بيانات تصحيح المقررات</a></button>
                </section>
                <section class="exit-buttons col-12" style="margin-top:20px;">
                    <button class="save manage-btn" type="button" style="width:80% ; padding: 15px;"><a href="{% url 'administration:resaults' %}" style="background-color:rgb(255, 179, 0); ">النتائج</a></button>
                </section>
            {% elif request.user.staff %}
                <section class="exit-buttons col-12" style="margin-top:20px;">
                    <button class="save manage-btn" type="button" style="width:80% ; padding: 15px;"><a href="{% url 'administration:upload_data' %}" style="background-color:rgb(255, 179, 0); ">إدخال البيانات</a></button>
                </section>
                <section class="exit-buttons col-12" style="margin-top:20px;">
                    <button class="save manage-btn" type="button" style="width:80% ; padding: 15px;"><a href="{% url 'administration:privileges' %}" style="background-color:rgb(255, 179, 0); ">وضع الصلاحيات</a></button>
                </section>
                <section class="exit-buttons col-12" style="margin-top:20px;">
                    <button class="save manage-btn" type="button" style="width:80% ; padding: 15px;"><a href="{% url 'unistruct:adding_subjects' %}" style="background-color:rgb(255, 179, 0); ">إضافة المقررات التي أقوم بتدريسها</a></button>
                </section>
                <section class="exit-buttons col-12" style="margin-top:20px;">
                    <button class="save manage-btn" type="button" style="width:80% ; padding: 15px;"><a href="{% url 'administration:subjects_report' %}" style="background-color:rgb(255, 179, 0); ">بيانات تسجيل المقررات</a></button>
                </section>
                <section class="exit-buttons col-12" style="margin-top:20px;">
                    <button class="save manage-btn" type="button" style="width:80% ; padding: 15px;"><a href="{% url 'researches:main' %}" style="background-color:rgb(255, 179, 0); ">الموضوعات البحثية</a></button>
                </section>
                <section class="exit-buttons col-12" style="margin-top:20px;">
                    <button class="save manage-btn" type="button" style="width:80% ; padding: 15px;"><a href="{% url 'administration:reports' %}" style="background-color:rgb(255, 179, 0); ">بيانات تصحيح المقررات</a></button>
                </section>
                <section class="exit-buttons col-12" style="margin-top:20px;">
                    <button class="save manage-btn" type="button" style="width:80% ; padding: 15px;"><a href="{% url 'administration:resaults' %}" style="background-color:rgb(255, 179, 0); ">النتائج</a></button>
                </section>
            {% elif request.user.control_head %}
                <section class="exit-buttons col-12" style="margin-top:20px;">
                    <button class="save manage-btn" type="button" style="width:80% ; padding: 15px;"><a href="{% url 'unistruct:adding_subjects' %}" style="background-color:rgb(255, 179, 0); ">إضافة المقررات التي أقوم بتدريسها</a></button>
                </section>
                <section class="exit-buttons col-12" style="margin-top:20px;">
                    <button class="save manage-btn" type="button" style="width:80% ; padding: 15px;"><a href="{% url 'researches:main' %}" style="background-color:rgb(255, 179, 0); ">الموضوعات البحثية</a></button>
                </section>
                <section class="exit-buttons col-12" style="margin-top:20px;">
                    <button class="save manage-btn" type="button" style="width:80% ; padding: 15px;"><a href="{% url 'administration:reports' %}" style="background-color:rgb(255, 179, 0); ">بيانات تصحيح المقررات</a></button>
                </section>
                <section class="exit-buttons col-12" style="margin-top:20px;">
                    <button class="save manage-btn" type="button" style="width:80% ; padding: 15px;"><a href="{% url 'administration:resaults' %}" style="background-color:rgb(255, 179, 0); ">النتائج</a></button>
                </section>
            {% elif user.dprtmngr %}
                <section class="exit-buttons col-12" style="margin-top:20px;">
                    <button class="save manage-btn" type="button" style="width:80% ; padding: 15px;"><a href="{% url 'administration:subjects_report' %}" style="background-color:rgb(255, 179, 0); ">بيانات تسجيل المقررات</a></button>
                </section>
                <section class="exit-buttons col-12" style="margin-top:20px;">
                    <button class="save manage-btn" type="button" style="width:80% ; padding: 15px;"><a href="{% url 'unistruct:adding_subjects' %}" style="background-color:rgb(255, 179, 0); ">إضافة المقررات التي أقوم بتدريسها</a></button>
                </section>
                <section class="exit-buttons col-12" style="margin-top:20px;">
                    <button class="save manage-btn" type="button" style="width:80% ; padding: 15px;"><a href="{% url 'researches:main' %}" style="background-color:rgb(255, 179, 0); ">الموضوعات البحثية</a></button>
                </section>
            {% else %}
                <section class="exit-buttons col-12" style="margin-top:20px;">
                    <button class="save manage-btn" type="button" style="width:80% ; padding: 15px;"><a href="{% url 'unistruct:adding_subjects' %}" style="background-color:rgb(255, 179, 0); ">إضافة المقررات التي أقوم بتدريسها</a></button>
                </section>
                <section class="exit-buttons col-12" style="margin-top:20px;">
                    <button class="save manage-btn" type="button" style="width:80% ; padding: 15px;"><a href="{% url 'researches:main' %}" style="background-color:rgb(255, 179, 0); ">الموضوعات البحثية</a></button>
                </section>
            {% endif %}
            
            <section class="exit-buttons col-12">
                <div class="row">
                    <div class="col-lg-12"><a href="{% url 'researches:main' %}">الرجوع</a></div>
                </div>
                <div class="row">
                    <div class="col-lg-12"><a  style="background-color: darkred;" href="{% url 'users:logout' %}">تسجيل الخروج</a></div>
                </div>
            </section>
        </div>
    </div>
{% endblock body %}
{% block script %}
    <script>

    </script>
{% endblock script %}

administration/templates/administration/resaults.html
{% extends 'base.html' %}
{% load static %}


{% block extrastyle %}
    <link rel="stylesheet" href="{% static 'css/admin-1.css' %}" />
    <link rel="stylesheet" href="{% static 'css/send-research.css' %}" />

    <style>
    .subjects .buttons .two div:first-of-type a,
    .subjects .buttons .three div:first-of-type a{
        background-color: #009687;
        border: none;
        color: #fff;
        width: 100%;
        padding: 10px 5px;
        display:inline-block;
    }
    </style>
{% endblock extrastyle %}
    

{% block title %}الرسائل البحثية - النتائج{% endblock title %}

{% block body %}
    <div class="box">
        <div class="row">
            <div class="col-lg-12 col-md-12 right">
                <div class="professor">
                    <img class="img-fluid" src="/media/images/professor2.png" alt="عضو هيئة تدريس" id="type-f-img">
                    <span id="name-span" class="name">
                        {{ request.user.name }} -
                        {% if request.user.admin %}
                            مدير المنصة
                        {% elif request.user.staff %}
                            عميد {{ request.user.faculty.name }}
                        {% elif request.user.control_head %}
                            رئيس كنترول الفرقة {{ request.user.team.name }}
                        {% endif %}
                    </span>
                    <p class="choosed title">
                        {% if request.user.admin %}
                            النتائج
                        {% elif request.user.staff %}
                            نتائج  {{ request.user.faculty.name }}
                        {% elif request.user.control_head %}
                            نتائج الفرقة {{ request.user.team.name }}
                        {% endif %}
                    </p>

                </div>

            </div>
            <section class="done-section">
                <div class="row">
                    <div class="col-lg-12 " style="padding: 0;">
                            <a id="done" class="done" href="{% url 'administration:approval' %}"> صفحة إعتماد النتائج ونسب النجاح</a>
                    </div>
                </div>

        </div>
        </section>
        <div class="col-lg-12 col-md-12 left subjects">

            <div class="row">
                <div class="col-12" id="selects">
                </div>
            </div>
        </div>
        <section class="col-12">
            <table class="first" class="hide" >
                <tr class="row2">
                    <th>إسم الطالب</th>
                    <th>المقرر</th>
                    <th>موضوع البحث</th>

                    <th>المقدمة <small>من10</small></th>
                    <th>محاور الموضوع <small>من20</small></th>
                    <th>المحتوى النظرى لمحاور الموضوع <small>من40</small></th>
                    <th>الاستخلاصات <small>من20</small></th>
                    <th>المراجع <small>من10</small></th>
                    <th>المجموع <small>من100</small></th>

                    <th>النتيجة</th>
                </tr>
                <tbody id="result-table">

                </tbody>
                <!-- <tr class="row2">
                    <td rowspan="3" class="name">محمد أحمد حسن السيد</td>
                    <td>الميكانيكا الحيوية في المجال الرياضي</td>
                    <td>الفرق بين التحليل الكيفي والتحليل الكمي</td>
                    <td><span class="passed" id="passed-span-1">مستوفي</span></td>
                </tr>
                <tr class="row2">
                    <td>الميكانيكا الحيوية في المجال الرياضي</td>
                    <td>الإدارة الرياضية</td>
                    <td><span class="passed" id="passed-span-1">مستوفي</span></td>
                </tr>
                <tr class="row2">
                    <td>علم النفس الرياضي</td>
                    <td>الفرق بين التحليل الكيفي والتحليل الكمي</td>
                    <td><span class="passed" id="passed-span-1">مستوفي</span></td>
                </tr> -->
<!-- ---------------------------------------------------------------------------------------------------- -->
            </table>
        </section>
        <section class="col-12 row">
            <section class="exit-buttons col-lg-{% if request.user.control_head and not request.user.staff %}4{% else %}6{% endif %}" style="margin-top: 0;">
                <button class="print" type="button" onclick="print()">  <i class="fas fa-print" style="margin-left: 10px;"></i>طباعة </button>
                
            </section>
            <section class="exit-buttons col-lg-{% if request.user.control_head and not request.user.staff %}4{% else %}6{% endif %}" style="margin-top: 0;">
                <button class="export" type="button" onclick="export_excel()"> <i class="fas fa-file-download" style="margin-left: 10px;"></i>استخراج النتيجة (excel) </button>
                
            </section>
            {% if request.user.control_head and not request.user.staff %}
                <section class="exit-buttons col-lg-4" style="margin-top: 0;">
                    <!-- <button class="export" type="button" onclick="export_excel()">  -->
                        <a style="background-color:orangered" href="{% url 'administration:download_compressed_folder' %}">تحميل جميع الابحاث</a>
                    <!-- </button> -->
                </section>
            {% endif %}
        </section>
        <section class="exit-buttons col-12">
            <div class="row">
                <div class="col-lg-6"><a href="{% url 'administration:choose' %}">الرجوع</a></div>
                <div class="col-lg-6"><a href="{% url 'users:logout' %}">تسجيل الخروج</a></div>
            </div>
        </section>
    </div>
</div>

{% endblock body %}
{% block script %}
    <script src="https://kit.fontawesome.com/467a5808c9.js" crossorigin="anonymous"></script>
    <script src="{% static 'js/xlsx.full.min.js' %}"></script>

    <script>
        var jstudents = [],
            jfaculties= [],
            user = {
                admin: {% if request.user.admin %} true {% else %} false {% endif %},
                staff: {% if request.user.staff %} true {% else %} false {% endif %},
                team: {% if request.user.team %} "{{ request.user.team.name }}" {% else %}""{% endif %},
                faculty:"{{ request.user.faculty.name }}" ,
            };
        {% for student in students %}
            rs = []
            {% if student.studnet_researches_list %}
                {% for student_research in student.studnet_researches_list %}
                    {% if student_research.corrected %}
                        rs.push({
                            name: "{{ student_research.research.name }}",
                            subject: "{{ student_research.research.subject.name }}",
                            references: "{{ student_research.references }}",
                            conclusions: "{{ student_research.conclusions }}",
                            content: "{{ student_research.content }}",
                            axes: "{{ student_research.axes }}",
                            intro: "{{ student_research.intro }}",
                            total: "{{ student_research.total }}",
                            passed: "{% if student_research.passed %}مستوفي{% else %}غير مستوفي{% endif %}"
                        })
                    {% endif %}
                {% endfor %}
                jstudents.push({
                    name: "{{ student.name }}",
                    faculty: "{{ student.faculty.name }}",
                    team: "{{ student.team.name }}",
                    researches: rs,
                })
            {% endif %}
        {% endfor %}
        {% for faculty in faculties %}
                tms=[]
                {% for team in faculty.teams_list %}
                    subjs = []
                    {% for subject in team.subjects_list %}
                        subjs.push({name: "{{ subject.name }}"})
                    {% endfor %}
                    tms.push({
                        name: "{{ team.name }}",
                        subjects: subjs,
                    })
                {% endfor %}
                jfaculties.push({
                    name: "{{ faculty.name }}",
                    teams: tms,
                })
        {% endfor %}
    </script>
    <script src="{% static 'js/administration/resaults.js' %}"></script>
{% endblock script %}