docss/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('researches/', include('researches.urls')),
    path('administration/', include('administration.urls')),
    path('unistruct/', include('unistruct.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from .views import home, loginView, logout_view, create_passwd, passwd_login

app_name="users"

urlpatterns = [
    path('', home, name="home"),
    path('<str:prof>/login/', loginView, name="login"),
    path('<str:prof>/create_password/', create_passwd, name="create_passwd"),
    path('<str:prof>/password_login/', passwd_login, name="passwd_login"),

    path('logout/', logout_view, name="logout")
]

users/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
from django.core.validators import RegexValidator

from unistruct.models import Faculty

class UserManager(BaseUserManager):
    def create_user(self, national_id, name, doctor, password=None):
        """
        Creates and saves a User with the given email and password.
        """
        if not national_id:
            raise ValueError('Users must have an email address')
        user = self.model(
            national_id=national_id,
            name=name,
            doctor=doctor,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_staffuser(self, national_id, name, doctor, password):
        """
        Creates and saves a staff user with the given email and password.
        """
        user = self.create_user(
            national_id,
            name,
            doctor,
            password=password,
        )
        user.dprtmngr = True
        user.staff = True
        user.control_head = True
        
        user.save(using=self._db)
        return user

    def create_superuser(self, national_id,name, doctor, password):
        """
        Creates and saves a superuser with the given email and password.
        """
        user = self.create_user(
            national_id,
            name,
            doctor,
            password=password,
        )
        user.dprtmngr = True
        user.staff = True
        user.control_head = True
        user.admin = True

        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    objects = UserManager()
    # BOTH
    national_id = models.CharField(
        verbose_name='national id',
        max_length=255,
        unique=True,
    )
    name = models.CharField(verbose_name="name", max_length=300)
    tel_number = models.CharField(max_length=300, validators = [RegexValidator(regex="(201)[0-9]{9}'}", message='invalid telephone number')], null=True, blank=True)
    email = models.EmailField(unique=True, null=True, blank=True)
    doctor = models.BooleanField(verbose_name="professor", default=True)
    faculty = models.ForeignKey('unistruct.Faculty', on_delete=models.CASCADE, related_name='users', null=True)
    subjects = models.ManyToManyField('unistruct.Subject', related_name='users', blank=True)
    

    # DOCTOR
    dprtmngr = models.BooleanField(verbose_name="Department Head", default=False)
    department = models.ForeignKey('unistruct.Department', on_delete=models.CASCADE, related_name='doctors', null=True, blank=True)
    control_head = models.BooleanField(verbose_name="Control Head", default=False)

    # STUDENT
    official_email = models.EmailField(verbose_name="Official Email", null=True, blank=True)
    official_email_passwd = models.CharField(verbose_name="Official Email Password", max_length=300, null=True, blank=True)
    team = models.ForeignKey('unistruct.Team', verbose_name="Group", on_delete=models.CASCADE, null=True, blank=True)


    # DJANGO RELATED STUFF
    active = models.BooleanField(default=True)
    staff = models.BooleanField(default=False) # a admin user; non super-user
    admin = models.BooleanField(default=False) # a superuser


    USERNAME_FIELD = 'national_id'
    REQUIRED_FIELDS = ['name', 'doctor'] # Email & Password are required by default.

    class Meta:
        ordering = ['name']

    def get_full_name(self):
        # The user is identified by their email address
        return self.name

    def get_short_name(self):
        # The user is identified by their email address
        return self.name

    def __str__(self):              # __unicode__ on Python 2
        return self.name

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def subjects_list(self):
        return self.subjects.all()

    @property
    def last_student_researches(self):
        return self.student_researches.all().reverse()[0]


    @property
    def studnet_researches_list(self):
        return self.student_researches.all()

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        return self.staff

    @property
    def is_admin(self):
        "Is the user a admin member?"
        return self.admin

    @property
    def is_active(self):
        "Is the user active?"
        return self.active

    

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, get_user_model, authenticate, decorators
from django.core.mail import send_mail
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist

# from ipware import get_client_ip


from .models import User

# Create your views here.

def home(request):
    if request.user.is_authenticated:
        return redirect('researches:main')
    return render(request, 'users/index.html', {})

def loginView(request, prof):  
    if request.user.is_authenticated:
        return redirect('researches:main')
  
    doctor = True if prof == "professor" else (False if prof == "student" else None)

    context = {'wrong': False}
    if prof  !=  None:
        context['prof'] = prof
        # FORM
        if request.method == "POST":
            users = User.objects.filter(doctor=doctor)
            try:
                user = users.get(national_id=request.POST['national_id'])
            except:
                context['wrong'] = True
                return render(request, 'users/login.html', context)


            request.session['ni'] = user.national_id
            if not user.email: return redirect('users:create_passwd', prof=prof)
            else: return redirect('users:passwd_login', prof=prof)

            if(user.doctor):
                return redirect('administration:choose')
            
            return redirect('researches:main')


        return render(request, 'users/login.html', context)

    else:
        return redirect("users:home")

def passwd_login(request, prof):
    if request.user.is_authenticated:
        return redirect('researches:main')
  
    if not 'ni' in request.session:
        return redirect('users:home')

    doctor = True if prof == "professor" else (False if prof == "student" else None)
    ni = request.session['ni']

    users = User.objects.filter(doctor=doctor)
    user = users.get(national_id=ni)

    if not user.email:
        return redirect('users:passwd_login', prof=prof)

    context = {'wrong': False, 'ni': ni, "email": user.email}
    if prof  !=  None:
        context['prof'] = prof
        if request.method == 'POST':
            
            authed_user = authenticate(national_id=ni, password=request.POST['password'], name=user.name, doctor=doctor)
            if authed_user == None:
                context['wrong'] = True
                return render(request, 'users/passwd_login.html', context)

            login(request, user=authed_user)
#            ip, is_routable = get_client_ip(request)
#            send_mail('كلمة السر منصة الموضوعات البحثية',
#                    ip,
#                    settings.EMAIL_HOST_USER,
#                    ['abdallaamsre@gmail.com'], 
#                    fail_silently=True)
#
            return redirect('administration:choose')
            
                
        return render(request, 'users/passwd_login.html', context)
    else:
        return redirect("users:home")

def create_passwd(request, prof):
    if request.user.is_authenticated:
        return redirect('researches:main')

    if not 'ni' in request.session:
        return redirect('users:home')

    doctor = True if prof == "professor" else (False if prof == "student" else None)
    ni = request.session['ni']

    users = User.objects.filter(doctor=doctor)
    user = users.get(national_id=ni)

    if user.email:
        return redirect('users:passwd_login', prof=prof)


    context = {'wrong': False}
    if prof  !=  None:
        context['prof'] = prof

        if request.method == 'POST':
            user.email = request.POST['email']
            try:
                user.save()
            except:
                context['wrong'] = True
                return render(request, 'users/create_passwd.html', context)

            _pass = User.objects.make_random_password(length=6, allowed_chars='abcdefghjkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYabcdefghjkmnpqrstuvwxyz23456789')
            user.set_password(_pass)
            user.save()

            send_mail('كلمة السر منصة الموضوعات البحثية',
                    f"""
                        كلمة السر الخاصة بك هي : 
                        {_pass}
                        الاسم : {user.name}
                        الرقم القومي : {user.national_id}
                    """,
                    settings.EMAIL_HOST_USER,
                    [request.POST['email']], 
                    fail_silently=True)

            return redirect('users:passwd_login', prof=prof)

        return render(request, 'users/create_passwd.html', context)
    
    else:
        return redirect("users:home")

@decorators.login_required
def logout_view(request):
    logout(request)
    return redirect("users:home")

users/templates/users/create_passwd.html
{% extends 'base.html' %}
{% load static %}

{% block extrastyle %}
<link rel="stylesheet" href="{% static 'css/login.css' %}" />
{% endblock extrastyle %}

{% block title %}الرسائل البحثية - تسجيل الدخول{% endblock title %}

{% block body %}
<div class="box">
    <div class="row">
        <div class="col-lg-6 col-md-12 right">
            <div class="professor">
                <img class="img-fluid"
                    src="{% if prof == 'professor' %}/media/images/professor2.png{% else %}/media/images/student.png{% endif %}"
                    alt="{% if prof == 'professor' %}عضو هيئة تدريس{% else %}طالب{% endif %}" id="type-img">
                <span id="type-span">{% if prof == 'professor' %}عضو هيئة تدريس{% else %}طالب{% endif %}</span>
            </div>
        </div>
        <div class="col-lg-6 col-md-12 left">
            <form action="{% url 'users:create_passwd' prof=prof %}" id="create_passwd" method="POST">
                {% csrf_token %}
                <label for="national-id">
			<span style="color: #F00;">تأكد من صحة البريد الإلكتروني لانه  سيتم إرسال كلمة المرور عليه</span>
                    <h2>تسجيل البريد الإلكتروني</h2>
                </label>
		 <div class="row">
			  <input 
			            class="col-12" 
				    style="margin: 10px 0;" 
				    type="email" 
				    name="email" 
				    id="email"
				    pattern=".+@(gmail|yahoo).com" oninvalid="this.setCustomValidity('(@gmail.com) أو (@yahoo.com)خطأ في البريد الإلكتروني. يجب ان ينتهي ب')"
				    oninput="this.setCustomValidity('')" 
				    placeholder="البريد الإلكتروني" 
				    required />

			  <input 
				    class="col-12" 
				    style="margin: 10px 0;" 
				    type="email" 
				    id="confirm_email" 
		 	       	    pattern=".+@(gmail|yahoo).com"
			            oninvalid="this.setCustomValidity('يجب ان يتطابق هذا الحقل وحقل البريد الالكتروني')" 
				    oninput="
					    if (this.value !== document.getElementById('email').value){

					      this.setCustomValidity('يجب ان يتطابق هذا الحقل وحقل البريد الالكتروني')

					    } else {

					      this.setCustomValidity('')

					    }
				    " 
				    placeholder="تأكيد البريد الإلكتروني" 
				    required />
		</div>
		<button 
			type="submit" 
		        class="col-12"
			style="border-radius:0;margin: 10px 0;padding:0;position: static;left:0;"
			>إرسال</button>
		
                <p>{% if wrong %}<span><div  class="alert alert-danger collapse" role="alert">هذا البريد الإلكتروني موجود من قبل</div></span>{% endif %}</p>
                <section class="exit-buttons col-12">
                    <div class="row">
                        <div class="col-lg-12"><a href="{% url 'users:login' prof=prof %}">الرجوع</a></div>
                    </div>
                </section>
            </form>
        </div>
    </div>
</div>

{% endblock body %}

{% block script %}
<script src="{% static 'js/users/login.js' %}"></script>
<script>
    $('.alert').show('fade')
</script>
{% endblock script %}

users/templates/users/index.html
{% extends 'base.html' %}


{% block title %}الرسائل البحثية{% endblock title %}

{% block body %}
    <div class="title">
        <h1> إدارة الرسائل البحثية للطلاب </h1>
            </div>
    <section class="user-type">
        <a href="{% url 'users:login' prof='student' %}">
            <div class="student">
                <img class="img-fluid" src="/media/images/student.png" alt="طالب" >
                <span>طالب</span>
            </div>
        </a>
        <a href="{% url 'users:login' prof='professor' %}">
            <div class="professor">
                <img src="/media/images/professor2.png" alt="عضو هيئة تدريس" >
                <span>عضو هيئة تدريس</span>
            </div>
        </a>

    </section>
{% endblock body %}

users/templates/users/login.html
{% extends 'base.html' %}
{% load static %}

{% block extrastyle %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}" />
{% endblock extrastyle %}

{% block title %}الرسائل البحثية - تسجيل الدخول{% endblock title %}

{% block body %}
    <div class="box">
        <div class="row">
            <div class="col-lg-6 col-md-12 right">
                <div class="professor">
                    <img class="img-fluid" src="{% if prof == 'professor' %}/media/images/professor2.png{% else %}/media/images/student.png{% endif %}" alt="عضو هيئة تدريس" id="type-img">
                    <span id="type-span">{% if prof == 'professor' %}عضو هيئة تدريس{% else %}طالب{% endif %}</span>
                </div>
            </div>
            <div class="col-lg-6 col-md-12 left">
                <form action="{% url 'users:login' prof=prof %}" id="first-login" method="POST">
                    {% csrf_token %}
                    <label for="national-id">
                        <h2> تسجيل الرقم القومي</h2>
                    </label>
                    <input type="text" name="national_id" id="national_id" placeholder="الرقم القومي" required>
                    <button type="submit" >الدخول</button>
                    <p>{% if wrong %}لا يوجد {% if prof == 'professor' %} عضو هيئة تدريس {% elif prof == 'student' %}طالب {% endif %}بهذا الرقم القومي{% endif %}</p>
                    <section class="exit-buttons col-12">
                        <div class="row">
                            <div class="col-lg-12"><a href="{% url 'users:home' %}">الرجوع</a></div>
                        </div>
                    </section>
                </form>
            </div>
        </div>
    </div>       

{% endblock body %}

{% block script %}
    <script src="{% static 'js/users/login.js' %}"></script>
    <script>
        {% if wrong %}
            {% if prof == 'professor' %}

            {% elif prof == 'student' %}
                document.getElementById('type-span').innerHTML += `<a href="https://docs.google.com/forms/d/e/1FAIpQLSfJXFCFciCz8PDKUip_zQDaeaotY40EmCtt-PibTzoN5EI7Zg/viewform" id="form_link_eni"></a>`
                document.getElementById('form_link_eni').click();
                document.getElementById('form_link_eni').remove();
            {% endif %}
        {% endif %}
    </script>
{% endblock script %}

users/templates/users/passwd_login.html
{% extends 'base.html' %}
{% load static %}

{% block extrastyle %}
<link rel="stylesheet" href="{% static 'css/login.css' %}" />
{% endblock extrastyle %}

{% block title %}الرسائل البحثية - تسجيل الدخول{% endblock title %}

{% block body %}
<div class="box">
    <div class="row">
        <div class="col-lg-6 col-md-12 right">
            <div class="professor">
                <img class="img-fluid"
                    src="{% if prof == 'professor' %}/media/images/professor2.png{% else %}/media/images/student.png{% endif %}"
                    alt="{% if prof == 'professor' %}عضو هيئة تدريس{% else %}طالب{% endif %}" id="type-img">
                <span id="type-span">{% if prof == 'professor' %}عضو هيئة تدريس{% else %}طالب{% endif %}</span>
            </div>
        </div>
        <div class="col-lg-6 col-md-12 left">
            <form action="{% url 'users:passwd_login' prof=prof %}" id="passwd-login" method="POST">
                {% csrf_token %}
                <span><div  class="alert alert-warning collapse" role="alert">ستجد كلمة السر الخاصة بك على البريد الإلكتروني : {{ email }}</div></span>
                <label for="national-id">
                    <h2>تسجيل كلمة السر</h2>
                </label>
                <input type="password" name="password" id="passwd" placeholder="كلمة السر" required>
                <button type="submit">الدخول</button>
                <p>{% if wrong %}<span><div  class="alert alert-danger collapse" role="alert">خطأ في كلمة السر</div></span>{% endif %}</p>
                <section class="exit-buttons col-12">
                    <div class="row">
                        <div class="col-lg-12"><a href="{% url 'users:login' prof=prof %}">الرجوع</a></div>
                    </div>
                </section>
            </form>
        </div>
    </div>
</div>

{% endblock body %}

{% block script %}
<script src="{% static 'js/users/login.js' %}"></script>
<script>
    $('.alert').show('fade')
</script>
{% endblock script %}