administration/urls.py
from django.urls import path

from .views import (
        choose, upload_data, 
        resaults, 
        privileges, 
        approval, 
        subjects_report, 
        reports,
        download_compressed_folder
    )

app_name = "administration"

urlpatterns = [
    path('', choose, name="choose"),
    path('upload/', upload_data, name="upload_data"),
    path('results/', resaults, name="resaults"),
    path('privileges/', privileges, name="privileges"),
    path('approval/', approval, name="approval"),
    path('subjects/data/', subjects_report, name="subjects_report"),
    path('subjects/reports/', reports, name="reports"),
    path('results/download-compressed-folder/', download_compressed_folder, name="download_compressed_folder")
]

docss/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('researches/', include('researches.urls')),
    path('administration/', include('administration.urls')),
    path('unistruct/', include('unistruct.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

researches/urls.py
from django.urls import path
from .views import (
        main, 
        create_topic, 
        select_topic, 
        upload_research, 
        correcting,
        students_resaults,
    )

app_name="researches"

urlpatterns = [
    path('', main, name="main"),
    path('<int:id>/doctor/topics/', create_topic, name="create_topic"),
    path('<int:id>/topics/select/', select_topic, name="select_topic_to_correct"),
    path('<int:sid>/<int:rid>/upload/', upload_research, name="upload_research"),
    path('<int:sid>/<int:rid>/correcting/', correcting, name="correcting"),
    path('students_resaults/', students_resaults, name="students_resaults"),
]

users/urls.py
from django.urls import path
from .views import home, loginView, logout_view, create_passwd, passwd_login

app_name="users"

urlpatterns = [
    path('', home, name="home"),
    path('<str:prof>/login/', loginView, name="login"),
    path('<str:prof>/create_password/', create_passwd, name="create_passwd"),
    path('<str:prof>/password_login/', passwd_login, name="passwd_login"),

    path('logout/', logout_view, name="logout")
]

researches/models.py
import os

from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.core.exceptions import ValidationError

from users.models import User
from unistruct.models import Subject
# Create your models here.


class Research(models.Model):
    name = models.TextField()
    subject = models.ForeignKey("unistruct.Subject", on_delete=models.CASCADE, related_name='researches')

    def __str__(self):
        return self.name

    @property
    def len_students(self):
        return len(self.student_researches.all())

    @property
    def student_researches_list(self):
        return self.student_researches.all()
        
def validate_file_extension(value):
    ext = os.path.splitext(value.name)[1]  # [0] returns path+filename
    valid_extensions = ['.pdf', '.doc', '.docx']
    if not ext.lower() in valid_extensions:
        raise ValidationError('Unsupported file extension.')

class StudentResearch(models.Model):
    research_file = models.FileField(validators=[validate_file_extension])
    research = models.ForeignKey(Research, on_delete=models.CASCADE, related_name='student_researches')
    students = models.ManyToManyField("users.User", related_name='student_researches')
    # References Field
    references = models.IntegerField(
        default=0,
        validators=[
            MaxValueValidator(10),
            MinValueValidator(0)
        ])

    # Conclusions Field
    conclusions = models.IntegerField(
        default=0,
        validators=[
            MaxValueValidator(20),
            MinValueValidator(0)
        ])

    # Content Field
    content = models.IntegerField(
        default=0,
        validators=[
            MaxValueValidator(40),
            MinValueValidator(0)
        ])

    # Axes Field
    axes = models.IntegerField(
        default=0,
        validators=[
            MaxValueValidator(20),
            MinValueValidator(0)
        ])

    # Intro Field
    intro = models.IntegerField(
        default=0,
        validators=[
            MaxValueValidator(10),
            MinValueValidator(0)
        ])

    seen = models.BooleanField(default=False)
    corrected = models.BooleanField(default=False)
    corrected_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"{self.research.name}"
    
    @property
    def passed(self):
        evaluation_items = [self.references, self.conclusions, self.content, self.axes, self.intro]
        return True if (sum(evaluation_items) >= 50) else False

    @property
    def total(self):
        evaluation_items = [self.references, self.conclusions, self.content, self.axes, self.intro]
        return sum(evaluation_items)

    @property
    def students_list(self):
        return self.students.all()

    @property
    def first_student(self):
        return self.students.first()

    def len_students_list(self):
        return len(self.students.all())

researches/views.py
import re
import json
import datetime

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, user_passes_test
from django.template import RequestContext

from users.models import User
from unistruct.models import Subject
from .models import Research, StudentResearch
# Create your views here.

@login_required
def main(request):
    if not request.user.doctor:
        if request.user.team.done:
            return redirect('researches:students_resaults')
    return render(request, 'researches/main.html', {})

@login_required
def create_topic(request, id):
    if not request.user.doctor:
        return redirect('researches:main')
    selected_subject = get_object_or_404(Subject, id=id)
    if not selected_subject in request.user.subjects.all():
        return redirect('researches:main')

    context = {'selected_subject': selected_subject}
    if request.method == "POST":
        Research.objects.filter(subject=selected_subject).delete()
        count = 0
        while count < int(request.POST['numr']):
            name = request.POST[f'subject-{count+1}']
            Research.objects.create(name=name, subject=selected_subject)

            count += 1

        return redirect('researches:main')
    return render(request, 'researches/create_topic.html', context)

@login_required
def select_topic(request, id):
    if not request.user.doctor:
        if request.user.team.done:
            return redirect('researches:students_resaults')

    selected_subject = get_object_or_404(Subject, id=id)
    if not selected_subject in request.user.subjects.all():
        return redirect('researches:main')
    context = {'selected_subject': selected_subject}
    if not request.user.doctor:
        selected_subject.rseen = True
        selected_subject.save()
        context['stu_h'] = False
        if request.user.student_researches.filter(research__subject=selected_subject):
            context['stu_h'] = request.user.student_researches.filter(research__subject=selected_subject).first()

    return render(request, 'researches/select_topic.html', context)


@login_required
def upload_research(request, sid, rid):
    # security
    if not request.user.doctor:
        if request.user.team.done:
            return redirect('researches:students_resaults')
    if request.user.doctor:
        return redirect('researches:main')

    # getting importatn information
    selected_subject = get_object_or_404(Subject, id=sid)

    if not selected_subject in request.user.subjects.all():
        return redirect('researches:main')

    selected_research = get_object_or_404(Research, id=rid)

    # initializing the context
    context = {'selected_subject': selected_subject,
               "open": (datetime.datetime.now() >= datetime.datetime(2020, 5,31) and datetime.datetime.now() < datetime.datetime(2020, 6,10))
    }
    # if the student has uploaded a research in this subject
    stu_h = request.user.student_researches.filter(research__subject=selected_subject)
    if stu_h:
        # if student trying to upload in other research
        if stu_h.first().research != selected_research:
            return redirect('researches:main')

        # sending student research with context
        context['stu_h'] = request.user.student_researches.filter(research__subject=selected_subject).first()

    # when the form in submitted
    if request.method == "POST":
        # loading colleagues data into dictionary called pst
        pst = json.loads(str(request.POST).replace('<QueryDict: ', '').replace(">",'').replace("'",'"'))

        # creating and setting file name
        fileName = f'{request.user.national_id[0:10]}'
        for colleague in pst.get('colleagues') if pst.get('colleagues') else []:
            colluser = User.objects.get(name=colleague)
            fileName+=f"-{colluser.national_id[0:10]}"
        request.FILES['file-7[]']._set_name(fileName)

        # delete any student research related to the student if exitsts and creating the new one
        request.user.student_researches.filter(research__subject=selected_subject).delete()
        stre = StudentResearch.objects.create(
            research_file=request.FILES['file-7[]'],
            research=selected_research)
        stre.students.add(request.user)

        # adding colleagues to student research
        for colleague in pst.get('colleagues') if pst.get('colleagues') else []:
            colluser = User.objects.get(name=colleague)
            stre.students.add(colluser)

        stre.save()
        return redirect('researches:upload_research', sid=selected_subject.id, rid=selected_research.id)

    # getting colleagues
    all_cols = request.user.team.students_list
    new_cols =[] 
    for col in all_cols:
        for sr in col.student_researches.all():
            if sr.research.subject == selected_subject:
                if sr == stu_h:
                    col.hasl = True
                    col.thisu = True
                else:
                    col.hasl = True
                    col.thisu = False
                break
            else:
                if sr == col.last_student_researches:
                    col.hasl = False
                    col.thisu = False

    context['cols'] = all_cols 
    context['selected_research']= selected_research = get_object_or_404(Research, id=rid)
    return render(request, 'researches/upload_research.html', context)

@login_required
def correcting(request, sid, rid):
    if not request.user.doctor:
        return redirect('researches:main')
    selected_subject = get_object_or_404(Subject, id=sid)
    if not selected_subject in request.user.subjects.all():
        return redirect('researches:main')
    selected_research = get_object_or_404(Research, id=rid)
    corrected_researches = StudentResearch.objects.filter(research=selected_research)
    for npr in corrected_researches.filter(seen=False):
        npr.seen = True
        npr.save()
    context = {
        'selected_subject': selected_subject,
        'selected_research': selected_research,
        'corrected_researches': corrected_researches,
    }
    if request.method == "POST":
        count = 1
        post = request.POST
        post_keys = list(request.POST.keys())
        while count < len(post_keys):
            item, num = post_keys[count].split('_')
            # i = -1
            # while (re.match(r'^-?\d+(?:\.\d+)?$', post_keys[count][i:]) is not None):
            #     num = post_keys[count][i:]
            #     i -= 1                  

            val = post[post_keys[count]]
            obj = corrected_researches.get(id=int(num))
            
            if item=="references": obj.references = int(val)
            elif item=="conclusions": obj.conclusions = int(val)
            elif item=="content": obj.content = int(val)
            elif item=="axes": obj.axes = int(val)
            elif item=="intro": obj.intro = int(val)
            else: raise ValueError('no input')
            
            obj.corrected = True
            obj.corrected_by = request.user

            obj.save()      

            count += 1

    return render(request, 'researches/correcting.html', context)

@login_required
@user_passes_test(
    lambda u: (not u.doctor) and (u.team.done),
    redirect_field_name="researches:main"
)
def students_resaults(request):
    return render(request, 'researches/students_resaults.html', {})

researches/templates/researches/create_topic.html
{% extends 'base.html' %}
{% load static %}

{% block extrastyle %}
    <link rel="stylesheet" href="{% static 'css/research-name.css' %}">
{% endblock extrastyle %}

{% block title %}الرسائل البحثية - اختيار المواضيع{% endblock title %}

{% block body %}
    <div class="box">
        <div class="row">
            <div class="col-lg-12 col-md-12 right">
                <div class="professor">
                    <img class="img-fluid" src="/media/images/professor2.png" alt="عضو هيئة تدريس" id="type-f-img">
                    <span id="name-span" class="name">{{ request.user.name }}</span>
                    <p>المقرر الذي قمت باختياره</p>
                    <p>{{ selected_subject.name }}</p>

                </div>
            </div>
                <!-- <section class="s-report">
                    <div class="row">
                        <div class="content hide" id="content">
                            <div class="col-12 r-item">
                                <h3 class="s-n" id="sn"> قمت بإضافة <span style="color:darkred;">5</span>  من المواضيع لهذا المقرر</h3>
                            </div>
                            <div class="col-12 r-item">
                                <h3 class="s-s" id="ss"><span style="color:darkred;">1000</span> من الطلاب يدرس هذا المقرر </h3>
                            </div>
                            <div class="col-12 r-item">
                                <h3 class="s-d" id="sd"> <span style="color:darkred;">1000</span>  من الطلاب قام بتقديم بحث في هذا المقرر </h3>
                            </div>
                        </div>
                        <button id="arrow" onclick="event.preventDefault()">
                            <div class="col-12 r-item arrow"><i class="fas fa-angle-down" id="arrowi"></i></div>
                        </button>
                    </div>
                </section> -->
            <div class="col-lg-12 col-md-12 left subjects">

                <div class="row">
                    <div class="col-12">
                        <span>قم باختيار مواضيع الأبحاث لهذا المقرر</span>
                    </div>
                    <form method="POST" action="{% url 'researches:create_topic' id=selected_subject.id %}" id="subject-form">
                        {% csrf_token %}
                        <input type="hidden" id="numr" name="numr"  />
                        <div class="upper" id="rinputs">
                            {% if selected_subject.researches_list %}
                                {% for research in selected_subject.researches_list %}
                                    {% if forloop.counter > 1 %}
                                        <div id="choose-sub-box-{{ forloop.counter }}">
                                            <div class="col-12 item" id = "r-box-{{ forloop.counter }}">
                                                <label for="subject-{{ forloop.counter }}">الموضوع {{ forloop.counter }}</label>
                                                <textarea name="subject-{{ forloop.counter }}" id="subject-{{ forloop.counter }}"   placeholder="الموضوع {{ forloop.counter }}" oninvalid="(this.value) ? this.setCustomValidity('هذا البحث موجود من قبل') : this.setCustomValidity('يجب ملئ هذا الحقل')" oninput="input_clicked(this)" required >{{ research.name }}</textarea>
                                            </div>
                                            <div class="col-12">
                                                <button type="button" id="remover-{{ forloop.counter }}" class = "remover" onclick = "rr(this)" >حذف الموضوع</button>
                                            </div>

                                    {% else %}
                                        <div id="choose-sub-box-1">
                                            <div class="col-12 item" id = "r-box-1">
                                                <label for="subject-1">الموضوع {{ forloop.counter }}</label>
                                                <textarea name="subject-1" id="subject-1"  placeholder="الموضوع {{ forloop.counter }}" oninvalid="(this.value) ? this.setCustomValidity('هذا البحث موجود من قبل') : this.setCustomValidity('يجب ملئ هذا الحقل')" oninput="input_clicked(this)" required>{{ research.name }}</textarea>
                                            </div>
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            {% else %}
                                <div id="choose-sub-box-1">
                                    <div class="col-12 item" id = "r-box-1">
                                        <label for="subject-1">الموضوع 1</label>
                                        <textarea name="subject-1" id="subject-1"  placeholder="الموضوع 1" oninvalid="(this.value) ? this.setCustomValidity('هذا البحث موجود من قبل') : this.setCustomValidity('يجب ملئ هذا الحقل')" oninput="input_clicked(this)" required></textarea>
                                    </div>
                                </div>
                            {% endif %}
                        </div>
                        <div class="col-12 buttons">
                            <div class="row two" id="buttons" >
                                
                                {% if selected_subject.len_researches_list < 3 %}
                                    <div class="col-6"><button type="submit">إنهاء</button></div>
                                    <div class="col-6"><button type="button" id="another-subject" onclick="addr()">اضافة موضوع آخر</button></div>
                                {% else %}
                                    <div class="col-12"><button type="submit">إنهاء</button></div>
                                {% endif %}
                            </div>
                            <!-- <div class="row three">
                                <div class="col-4"><button type="submit">إنهاء</button></div>
                                <div class="col-4"><button type="button">اضافة موضوع آخر</button></div>
                                <div class="col-4"><button type="button">حذف الموضوع</button></div>
                            </div> -->
                        </div>
                    </form>
                </div>
            </div>
            <section class="exit-buttons col-12">
                <div class="row">
                    <div class="col-lg-6"><a href="{% url 'researches:main' %}">الرجوع</a></div>
                    <div class="col-lg-6"><a href="{% url 'users:logout' %}">تسجيل الخروج</a></div>
                </div>
            </section>
        </div>
    </div>

{% endblock body %}

{% block script %}

    <script src="{% static 'js/researches/create_topic.js' %}"></script>
    <script>
    numr.value = "0"
    {% if selected_subject.researches_list %}
        {% for research in selected_subject.researches_list %}
            numr.value = `${Number(numr.value) + 1}`
        {% endfor %}
    {% else %}
        numr.value = "1"
    {% endif %}

    function input_clicked(trgt){
        trgt.setCustomValidity('')
        for(let inpt of document.getElementById("subject-form").querySelectorAll('input[type="text"]')){
            console.log(inpt)

            if(inpt.value == trgt.value){
                trgt.setCustomValidity('هذا البحث موجود من قبل')
                break;
            }
        }
    }
</script>
{% endblock script %}

researches/templates/researches/main.html
{% extends 'base.html' %}
{% load static %}


{% block extrastyle %}
    <link rel="stylesheet" href="{% static 'css/subjects.css' %}" />
    <style>
        .box .left span.choose-span{
            color:#078194;
            font-size: 2em;
        }
	.ofem{
		display:block;
		padding:10px;
		color: darkred;
	}
    </style>
{% endblock extrastyle %}
    

{% block title %}الرسائل البحثية - اختيار المقررات{% endblock title %}

{% block body %}
    <div class="box">
        <div class="row">
            <div class="col-lg-12 col-md-12 right">
                <div class="professor">
                    <img class="img-fluid" src="{% if request.user.doctor %}/media/images/professor2.png{% else %}/media/images/single-student.png{% endif %}" alt="مستخدم" id="type-f-img">
                    <span id="name-span" class="name">{{ request.user.name }}</span>
                    <p>مرحبا بك على المنصة الخاصة بإدارة الرسائل البحثية </p>
                </div>
            </div>
            <div class="col-lg-12 col-md-12 left subjects" id="subjects">

                <div class="row">
                    <div class="col-12">
			    {% if not request.user.doctor %}
			    <span class="ofem" >البريد الإلكتروني الجامعي : {{ request.user.official_email }}</span>
			    <span class="ofem" style="margin-bottom:10px;">كلمة السر : {{ request.user.official_email_passwd }}</span>
			    {% endif %}
                        <span class="choose-span"> قم بإختيار المقرر</span>
                    </div>
                    {% if request.user.subjects_list %}
                        {% for subj in request.user.subjects_list %}
			<div class="col-12 item"{% if not request.user.doctor %}{% if not subj.team == request.user.team %}style="background-color:#F00;"{% endif %}{% endif %}>
                                <a href="
                                {% if request.user.doctor %}
				    {% if subj.id == 363 %}
				    	http://sea.alexu.edu.eg/index.php/ar/2015-06-11-09-54-18/2/3238-2020-05-18-15-41-51
				    {% else %}
					    {% if subj.rseen %}
						{% url 'researches:select_topic_to_correct' id=subj.id %}
					    {% else %}
						{% url 'researches:create_topic' id=subj.id %}
					    {% endif %}
				    {% endif %}
                                {% else %}
				    {% if subj.id == 363 %}
				    	http://sea.alexu.edu.eg/index.php/ar/2015-06-11-09-54-18/2/3238-2020-05-18-15-41-51
				    {% else %}
					    {% url 'researches:select_topic_to_correct' id=subj.id %}
				    {% endif %}
				    {% endif %}"{% if subj.id == 363 %}target="_blank"{% endif %}>
					<button>{{ subj.name }}{% if not request.user.doctor %}{% if not subj.team == request.user.team %} - تخلف{% endif %}{% endif %}
					{% if subj.id == 363 %}
						<br />
						لمزيد من المعلومات حول الموضوعات البحثية لمقرر التربية العسكرية وتسليم المقالة البحثية علي منصة الجامعة يرجي الدخول علي موقع الكلية بالضغط هنا
						{% endif %}
					
					</button>
                                </a>
                                <span>{{ subj.section.department.faculty }}</span>
                                <span>{{ subj.team.name }}</span>
                                {% if request.user.doctor %}
                                    <section class="s-report">
                                        <div class="row">
                                            <div class="content hide" id="content{{ forloop.counter }}">
                                                <div class="col-12 r-item">
                                                    <h3 class="s-n" id="sn"> قمت بإضافة <span style="color:darkred;">{{ subj.len_researches_list }}</span>  من المواضيع لهذا المقرر</h3>
                                                </div>
                                                <div class="col-12 r-item">
                                                    <h3 class="s-s" id="ss"><span style="color:darkred;">{{ subj.len_students }}</span> من الطلاب يدرس هذا المقرر </h3>
                                                </div>
                                                <div class="col-12 r-item">
                                                    <h3 class="s-d" id="sd"> <span style="color:darkred;">{{ subj.len_student_researches_list }}</span>  من الطلاب قام بتقديم بحث في هذا المقرر </h3>
                                                </div>
                                            </div>
                                            <button id="arrow{{ forloop.counter }}" onclick="show_data(this)">
                                                <div class="col-12 r-item arrow"><i class="fas fa-angle-down" id="arrowi{{ forloop.counter }}"></i></div>
                                            </button>
                                        </div>
                                    </section>
                                {% endif %}
                            </div>
                        {% endfor %}
                    {% else %}
                        <div class="col-12 item">
                            ليس هناك اي مقررات مسجلة لهذا المستخدم
                        </div>
                    {% endif %}
                    </div> 
                </div>
            </div>
            <section class="exit-buttons col-12">
                {% if request.user.doctor %}
                    <div class="row">
                        <div class="col-lg-12"><a href="{% url 'administration:choose' %}">الرجوع</a></div>
                    </div>
                {% endif %}
                <div class="row">
                    <div class="col-lg-12"><a href="{% url 'users:logout' %}" style="background-color: darkred;">تسجيل الخروج</a></div>
                </div>
            </section>
        </div>
    </div>

{% endblock body %}

{% block script %}
    <script src="https://kit.fontawesome.com/467a5808c9.js" crossorigin="anonymous"></script>
    <script>
try {
    // document.getElementById("arrow").onclick = 
    function show_data (e) {
        num = e.id.slice(-1)
        i = -1
        while(!isNaN(Number(e.id.slice(i)))){
            num = e.id.slice(i)
            i -= 1;
        }        
        document.getElementById(`content${num}`).classList.toggle("hide");
        document.getElementById(`arrowi${num}`).classList.toggle("fa-angle-down");
        document.getElementById(`arrowi${num}`).classList.toggle("fa-angle-up");
    }
} catch{ }
    </script>
{% endblock script %}

researches/templates/researches/students_resaults.html
{% extends 'base.html' %}
{% load static %}


{% block extrastyle %}
    <link rel="stylesheet" href="{% static 'css/admin-1.css' %}">
    <link rel="stylesheet" href="{% static 'css/send-research.css' %}">
    <link rel="stylesheet" href="{% static 'css/result-stu.css' %}">
{% endblock extrastyle %}
    

{% block title %}الرسائل البحثية - النتائج{% endblock title %}

{% block body %}
    <div class="box">
        <div class="row">
            <div class="col-lg-12 col-md-12 right">
                <div class="professor">
                    <img class="img-fluid" src="/media/images/single-student.png" alt="طالب" id="type-f-img">
                    <span id="name-span" class="name">{{ request.user.name }}</span>
                    <p class="choosed name">النتيجة النهائية</p>
                </div>
            </div>
            <section class="col-12">                
                <table class="first" class="hide" id="approval-table">
                    <tr class="row2">
                        <th>المقرر</th>
                        <th>موضوع البحث</th>
                        <th>النتيجة</th>
                    </tr>

                    {% for sr in request.user.studnet_researches_list %}
                        <tr class="row2">
                            <td class="name">{{ sr.research.subject }}
			   	{% if sr.research.subject.team  request.user.team %}
				- تخلف
				{% endif %}
			    </td>
                            <td>{{ sr.research.name }}</td>
                            <td>
                                <span class="{% if sr.passed %}passed{% else %}not-passed{% endif %}" id="{% if sr.passed %}passed{% else %}not-passed{% endif %}-span">
                                    {% if sr.passed %}
                                        مستوفي
                                    {% else %}
                                        غير مستوفي
                                    {% endif %}
                                </span>         
                            </td>
                        </tr>                    
                    {% endfor %}
                </table>         
            </section>
            <section class="exit-buttons col-12">
                <button class="print"  type="submit" onclick="print()"> <i class="fas fa-print" style="margin-left: 10px;"></i>طباعة</button>
            </section>
            <section class="exit-buttons col-12">
                <div class="row">
                    <div class="col-lg-12"><a  style="background-color: darkred;" href="{% url 'users:logout' %}">تسجيل الخروج</a></div>
                </div>
            </section>
        </div>
    </div>
{% endblock body %}

{% block script %}
    <script></script>
{% endblock script %}